# experiments.yaml — canonical matrix for runs (Phase 1, 2, 2b, pharmacogenomic)

- id: p1_tcga_baseline                # Phase 1 — TCGA baseline (binary proxy)
  track: tcga
  endpoint: binary
  model: logistic
  missingness: [none, mcar_20, block_proteome, mnar_tissue]
  confounds: {use_residualize: false, use_combat: false, confound_cols: [tissue, batch]}
  ood: {leave_tissue_out: false}
  uncertainty: {conformal: false, mc_dropout: false, ensembles: 0}

- id: p2_tcga_impute_matrix           # Phase 2 — handle missing modality via matrix completion
  track: tcga
  endpoint: binary
  model: gbm
  imputation: {strategy: soft_impute, target_modalities: [proteome]}
  missingness: [block_proteome]
  confounds: {use_residualize: true, use_combat: false, confound_cols: [tissue, batch]}
  ood: {leave_tissue_out: false}
  uncertainty: {conformal: true, mc_dropout: false, ensembles: 0}

- id: p2b_tcga_deconf_ood             # Phase 2b — deconfounding + leave-tissue-out OOD
  track: tcga
  endpoint: binary
  model: rf
  missingness: [none, block_proteome]
  confounds: {use_residualize: true, use_combat: false, confound_cols: [tissue, batch]}
  ood: {leave_tissue_out: true}
  uncertainty: {conformal: true, mc_dropout: false, ensembles: 5}

- id: p1_pg_baseline_gdsc             # Pharmacogenomic track — GDSC baseline (regression)
  track: gdsc
  endpoint: regression
  model: gbm
  missingness: [none, mcar_20, block_proteome]
  confounds: {use_residualize: true, use_combat: false, confound_cols: [tissue]}
  ood: {leave_tissue_out: false}
  uncertainty: {conformal: true, mc_dropout: false, ensembles: 0}

globals:
  features:
    use_kg: false                     # enable later when KG features land
  api:
    expose_explain: true
